// Code generated by tygo. DO NOT EDIT.

//////////
// source: release.go

export type ReleaseType = string;
export type SpecialLabel = string;
export type SourceName = string;
export const TypeAlbum: ReleaseType = "album";
export const TypeTrack: ReleaseType = "track";
export const SpecialBestNewAlbum: SpecialLabel = "Best New Album";
export const SpecialBestNewTrack: SpecialLabel = "Best New Track";
export const SpecialBestNewReissue: SpecialLabel = "Best New Reissue";
export const SourceBandcamp: SourceName = "Bandcamp";
export const SourceNPR: SourceName = "NPR";
export const SourcePitchfork: SourceName = "Pitchfork";
export const SourceStereogum: SourceName = "Stereogum";
export const SourceXXL: SourceName = "XXL";
export interface Artist {
  Model: any /* gorm.Model */;
  name: string;
  releases: Release[];
}
export interface Release {
  Model: any /* gorm.Model */;
  name: string;
  artists: Artist[];
  publish_date: string;
  link: string;
  source: SourceName;
  release_type: ReleaseType;
  special?: SpecialLabel;
}
